export enum MoneyHeaders {
  SRoth = 'SRoth',
  STrad = 'STrad',
  SSave = 'SSave',
  Baird = 'Baird',
  K = '401k',
  HSA = 'HSA',
  Crypto = 'Crypto',
  Treasury = 'Treasury',
  Metal = 'Metal',
  ACheck = 'ACheck',
  ASpend = 'ASpend',
  ASave = 'ASave',
  SoFi = 'SoFi',
  Cash = 'Cash',
  Kohler = 'Kohler',
  Apple = 'Apple',
  Discover = 'Discover',
  Chase = 'Chase',
  Prime = 'Prime',
  Verizon = 'Verizon',
}