export const API_KEY_ONE = 'API_KEY_ONE';
export const GOOGLE_EMAIL = 'GOOGLE_EMAIL';
export const GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
export const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
export const TEST_SPREADSHEET = 'TEST_SPREADSHEET';
export const MONEY_SPREADSHEET = 'MONEY_SPREADSHEET';